### ISSUE TITLE
Error building: 'global::' already contains a definition for 'Correlation'

### ISSUE THREAD

**Issue by cboulay** [Fredz66/PS-Move-Setup#1]
I'm receiving the following error when attempting to build the project:

`Assets/Src/ControllerRegistration.cs(14,15): error CS0101: The namespace`global::' already contains a definition for `Correlation'`

I'm also getting the following error:

`System.IO.FileNotFoundException: Could not find file "D:\SachsLab\Tools\VR\PSMove\PS-Move-Setup\Assets\Plugins\MathNet.Numerics\MathNet.Numerics.dll.mdb".`

**Comment by Fredz66** [comment]
Sorry I pushed the code in a hurry. I think removing the files BaseCoregistration.cs and HornCoregistration.cs in Assets\Src should remove the first error.

No idea for the second error, maybe it's related to the first one. If not try to build for 64 bit if it wasn't already the case.

**Comment by cboulay** [comment]
Fixed in PR #2
