### ISSUE TITLE
Needs instructions

### ISSUE THREAD

**Issue by cboulay** [Fredz66/PS-Move-Setup#3]
What do I do after I run the .exe?

Should the controller be tied to the HMD before I run the exe?
How do I stop collecting data points and test the coregistration?

This info can go in the README, but some on-screen instructions would be nice.

**Comment by Fredz66** [comment]
Yes the controller needs to be tied to the DK2. Then you need to move both over the field of view of both cameras, I think rotating the attachment should help also.

I'm still working on rotation, when I'm done with this I'll revamp the utility to make it more straightforward for users.
