### ISSUE TITLE
HMD pitch is off

### ISSUE THREAD

**Issue by cboulay** [Fredz66/PS-Move-Setup#4]
The 3D representation of my DK2 has the wrong initial rotation, and when I pitch it up, the game object pitches down. Is it just me?

**Comment by Fredz66** [comment]
In the last commit I forgot that I had already written code for testing the rotation calibration and I pushed that in a hurry after your last e-mail, sorry about that. You need to replace this code with the one that uses the proper optical orientation tracking.

I think uncommenting :
`//RotatedPosition = Quaternion.Inverse(dk2.Orientation) * (DummyPosition - dk2.Position) + dk2.Position;`
and replacing :
`transform.rotation = MARGOrientation;`
with :
`transform.rotation = RotatedPosition;`
in MoveController.cs

and uncommenting :
`//transform.rotation = pose.orientation;`
in DK2Controller.cs should be enough.
